#!/bin/bash
cd "$(dirname "$0")"
source /home/rinkoa/OpenFOAM-v2012/etc/bashrc

echo "=== Re=30000, U=0.45 m/s ==="
blockMesh 2>&1 | tee log.blockMesh
snappyHexMesh -overwrite 2>&1 | tee log.snappyHexMesh
checkMesh 2>&1 | tee log.checkMesh
decomposePar 2>&1 | tee log.decomposePar
mpirun -np 4 pimpleFoam -parallel 2>&1 | tee log.pimpleFoam
reconstructPar 2>&1 | tee log.reconstructPar
