#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

cp 0/alpha.water.org 0/alpha.water

runApplication blockMesh
runApplication funkySetFields -time 0
runApplication funkySetBoundaryField -time 0
runApplication $application

# ----------------------------------------------------------------- end-of-file
